name: Continuous Integration

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} --image ${{ secrets.ACR_NAME }}.azurecr.io/your-app:${{ github.sha }} .
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}